### ISSUE TITLE
Osha7 FLOSS and Code Hackathon Submission

### ISSUE THREAD

**Issue by osha7** [floss-and-code/stripe-hackathon#12]
## Describe your submission
https://github.com/osha7/og-github-floss-subs
This repository uses Stripe's(Thor's) template for subscription purchases to build a template for one-off purchases.  The readme.md file has been updated, a Google 3rd party oauth login has been added, 3 pages have been added as placeholders: company about page (also available in logo links), blog page, and career page.  The products now have a quantity input field and the Account page has been updated so that users may update their Names.  

### [In what way did you change the template?](https://github.com/floss-and-code/stripe-hackathon#the-challenge)

- [ ] Copy
- [x] Design
- [ ] Improve

### [Team members](https://github.com/floss-and-code/stripe-hackathon/blob/main/FAQs.md#can-i-submit-as-a-team)

_If you worked with others, please list their GitHub Handles (Limit 3)_ 
ReginaF2012 (https://github.com/ReginaF2012)

### [Link to the Blog post describing your submission and experience](https://github.com/floss-and-code/stripe-hackathon/blob/main/rules.md#winner-selection-and-notification)

https://ogroetz.medium.com/i-just-did-what-floss-and-code-2020-9951eb2b6cf4

**Comment by bdougie** [comment]
@osha7 thanks for your submission and sharing your blog post. I will follow up via email about your GitHub swag.
